export const carData = {
  "Audi": ["A1", "A3", "A4", "A6", "Q3", "Q5", "Q7", "e-tron"],
  "BMW": ["1-es sorozat", "2-es sorozat", "3-as sorozat", "4-es sorozat", "5-ös sorozat", "X1", "X3", "X5", "i3", "i4"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mustang", "Ranger", "Mondeo"],
  "Mercedes-Benz": ["A-osztály", "B-osztály", "C-osztály", "E-osztály", "GLA", "GLC", "EQA", "EQC", "Sprinter"],
  "Opel": ["Corsa", "Astra", "Mokka", "Grandland", "Crossland", "Insignia"],
  "Skoda": ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  "Suzuki": ["Swift", "Ignis", "Vitara", "S-Cross", "Jimny"],
  "Toyota": ["Yaris", "Corolla", "C-HR", "RAV4", "Hilux", "Land Cruiser", "Prius"],
  "Volkswagen": ["Polo", "Golf", "T-Roc", "Tiguan", "Passat", "ID.3", "ID.4", "Touran", "Transporter"],
  "Hyundai": ["i10", "i20", "i30", "Tucson", "Kona", "Santa Fe", "IONIQ 5"],
  "Kia": ["Picanto", "Rio", "Ceed", "Sportage", "Niro", "Sorento", "EV6"],
  "Renault": ["Clio", "Megane", "Captur", "Kadjar", "Austral", "Duster", "Zoe"],
  "Peugeot": ["208", "308", "2008", "3008", "5008", "Partner"],
  "Citroën": ["C3", "C4", "C5 Aircross", "Berlingo", "Cactus"],
  "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf"],
  "Honda": ["Jazz", "Civic", "HR-V", "CR-V"],
  "Mazda": ["Mazda2", "Mazda3", "CX-5"],
  "Volvo": ["XC40", "XC60", "XC90", "S60", "S90"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Dacia": ["Sandero", "Duster", "Logan", "Jogger"],
  "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  "Fiat": ["500", "Panda", "Tipo"],
  "Mitsubishi": ["Outlander", "ASX", "Eclipse Cross"],
  "Jaguar": ["F-Pace", "E-Pace", "I-Pace", "XE", "XF"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Discovery", "Defender", "Evoque", "Velar"],
  "Porsche": ["911", "Cayenne", "Macan", "Taycan"],
  "Lexus": ["IS", "ES", "RX", "NX", "UX"],
  "Subaru": ["Impreza", "Forester", "Outback", "XV"],
  "Jeep": ["Wrangler", "Grand Cherokee", "Compass", "Renegade"],
  "Mini": ["Cooper", "Countryman"],
  "Alfa Romeo": ["Giulia", "Stelvio"],
  "Cupra": ["Formentor", "Leon", "Ateca"],
  "MG": ["ZS", "HS", "Marvel R", "MG4"],
  "Polestar": ["Polestar 2", "Polestar 3"],
  "BYD": ["Atto 3", "Han", "Tang"],
  "NIO": ["ES8", "ET7", "EL7"],
  "XPeng": ["P7", "G9"],
  "Smart": ["Fortwo", "Forfour", "EQ fortwo", "EQ forfour"],
  "SsangYong": ["Korando", "Tivoli", "Rexton"],
  "Chevrolet": ["Corvette", "Camaro", "Silverado", "Equinox", "Malibu"],
  "GMC": ["Sierra", "Yukon", "Terrain"],
  "Cadillac": ["Escalade", "XT5", "CT5"],
  "Lincoln": ["Navigator", "Aviator", "Corsair"],
  "Chrysler": ["Pacifica", "Voyager"],
  "Dodge": ["Challenger", "Charger", "Durango"],
  "Ram": ["1500", "2500", "3500"],
  "Acura": ["MDX", "RDX", "TLX"],
  "Infiniti": ["Q50", "QX60"],
  "Genesis": ["G70", "G80", "GV80"],
  "Bugatti": ["Chiron"],
  "Lamborghini": ["Aventador", "Huracán", "Urus"],
  "Ferrari": ["Roma", "Portofino", "SF90 Stradale"],
  "McLaren": ["720S", "Artura"],
  "Rolls-Royce": ["Phantom", "Ghost", "Cullinan"],
  "Bentley": ["Continental GT", "Flying Spur", "Bentayga"],
  "Aston Martin": ["Vantage", "DB11", "DBS Superleggera"],
  "Lotus": ["Emira", "Evija"],
  "Maserati": ["Ghibli", "Levante", "Quattroporte"],
  "Pagani": ["Huayra", "Zonda"],
  "Koenigsegg": ["Jesko", "Gemera"],
  "Rimac": ["Nevera"],
  "Lucid": ["Air"],
  "Rivian": ["R1T", "R1S"],
  "Isuzu": ["D-Max", "MU-X"],
  "Alpine": ["A110"],
  "Buick": ["Encore", "Envision", "LaCrosse"],
  "Chrystler": ["300"],
  "Hennessey": ["Venom F5"],
  "Lancia": ["Ypsilon", "Delta"],
  "Morgan": ["Plus Four", "Plus Six"],
  "Saab": ["9-3", "9-5"],
  "Shelby": ["Cobra", "GT500"],
  "Trabant": ["601"],
  "Lada": ["Vesta", "Granta", "Niva"]
};